### PR TITLE
Fall22 overhaul

### PR DESCRIPTION
**Pull request by jeseekia**
This PR incorporates
- theme updates
- shared file organization
- file references

The goal of this PR is 
- to share the GDI theme across all workshop files
- to include template slides like pre- and post-event slides

There is a demo workshop directory for copying to make new workshops.
There is a dedicated workshop directory for intro-python that mirrors multi-session workshops.
Updating the technical content for any workshops is *out of scope* for this PR.
Shared assets are in the top of the directory.

### CODE REVIEW

**Comment by pamelafox** [comment]
Hi @jeseekia - I think this repo is where I originally hosted materials back when I gave the course, right? Will those materials still be available in a folder? I like to be able to reference them sometimes. Thanks!

**Comment by jeseekia** [comment]
> Hi @jeseekia - I think this repo is where I originally hosted materials back when I gave the course, right? Will those materials still be available in a folder? I like to be able to reference them sometimes. Thanks!

Hey @pamelafox1! Nice web apps workshop today! The folders for each workshop still contain the exercise files and other pre-existing material. Some of the content changes may be updated in the future as other instructors are iterating on this, but I believe everything your looking for should still exist. Also this repo wasn't deployed for some reason so it will be getting a GH Pages deployment.

What materials are you looking to reference? Since these workshops are being updated and we're reorganizing contents, it'd be helpful to know what you're pointing students to.

Python 1 and 2 were split into individual directories and the index pages of those reference all the relevant slides and exercise links.

**Review by jeseekia — COMMENTED** [review]
One other consideration is whether to move the intro-python-1-fa22 slides to another branch since that update belongs to

**Comment by jeseekia** [comment]
These changes are being merged, however, https://github.com/girldevelopit/gdi-python/tree/early-2022-material is a branch of main as it exists now.

**Pull request merged**
